return {

	{
		Id = "FrozenPeel",
		Name = "Frozen Peel",

		Image = "",

		Rarity = "Epic",

		Price = 2500,

		Currency = "Coins",
	},
	{
		Id = "SleepyBanana",
		Name = "Sleepy Banana",
		Image = "rbxassetid://135962056138033",
		Rarity = "Common",
		Price = 2000,
		Currency = "Coins",
	},
	{
		Id = "GalaxyBanana",
		Name = "Galaxy Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Epic",
		Price = 4999,
		Currency = "Coins",
	},

	{
		Id = "RainbowPeel",
		Name = "Rainbow Peel",
		Image = "",
		Rarity = "Legendary",
		Price = 6000,
		Currency = "Coins",
	},

}