return {
		{
		Id = "Coins500",
		Name = "500 Coins",
		Image = "rbxassetid://82201314708550",
		Rarity = "Rare",
		Price = 29,
		Currency = "Robux",
		Amount = 500,
		ProductId = 3671878790
	},
	{
		Id = "Coins1000",
		Name = "1000 Coins",
		Image = "rbxassetid://106584451826934",
		Rarity = "Rare",
		Price = 49,
		Currency = "Robux",
		Amount = 1000,
		ProductId = 3673353904
	},

	{
		Id = "Coins3000",
		Name = "3000 Coins",
		Image = "rbxassetid://88032550394310",
		Rarity = "Epic",
		Price = 199,
		Currency = "Robux",
		Amount = 3000,
		ProductId = 3673371784
	},

}