local GamePacks = {

	{
		Id = "StarterPack",

		Name = "Starter Pack",

		Image = "rbxassetid://111415095133320",

		Rarity = "Legendary",

		Price = 99,
		Currency = "Robux",

		Rewards = {

			Coins = {
				Amount = 2500,
				Icon = "rbxassetid://106584451826934",
			},

			Skins = {
				{
					Id = "SleepyBanana",
					Image = "rbxassetid://136115997706635",
				},
			},

			BananaSkins = {
				{
					Id = "GalaxyBanana",
					Image = "rbxassetid://77545653351880",
				},
				{
					Id = "SleepyBanana",
					Image = "rbxassetid://135962056138033",
				},
			},

		},
	},

	{
		Id = "EpicPack",

		Name = "Epic Pack",

		Image = "rbxassetid://137906952419654",

		Rarity = "Mythic",

		Price = 199,
		Currency = "Robux",

		Rewards = {

			Coins = {
				Amount = 2500,
				Icon = "rbxassetid://106584451826934",
			},

			Skins = {
				{
					Id = "SleepyBanana",
					Image = "rbxassetid://136115997706635",
				},
				{
					Id = "CoolBanana",
					Image = "rbxassetid://122492456684024",
				},
			},

			BananaSkins = {
				{
					Id = "GalaxyBanana",
					Image = "rbxassetid://77545653351880",
				},
				{
					Id = "SleepyBanana",
					Image = "rbxassetid://135962056138033",
				},
			},

		},
	},

}

return GamePacks