local Skins = {

	{
		Id = "SimpleBanana",
		Name = "Simple Banana",
		Image = "rbxassetid://101709420966439",
		Rarity = "Common",
		Price = 0,
		Currency = "Coins",
	},

	{
		Id = "ChiefBanana",
		Name = "Chief Banana",
		Image = "rbxassetid://122492456684024",
		Rarity = "Common",
		Price = 1200,
		Currency = "Coins",
	},

	{
		Id = "DeliveryBanana",
		Name = "Delivery Boy",
		Image = "rbxassetid://122492456684024",
		Rarity = "Common",
		Price = 2200,
		Currency = "Coins",
	},
	{
		Id = "EnginnerBanana",
		Name = "Enginner Banana",
		Image = "rbxassetid://103958840548469",
		Rarity = "Common",
		Price = 5999,
		Currency = "Coins",
	},

	{
		Id = "DreamyBanana",
		Name = "Dreamy Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Common",
		Price = 12999,
		Currency = "Coins",
	},

	
	{
		Id = "NinjaWarrior",
		Name = "Ninja Warrior",
		Image = "rbxassetid://77545653351880",
		Rarity = "Rare",
		Price = 12999,
		Currency = "Coins",
	},
		
	{
		Id = "PirateBanana",
		Name = "Pirate Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Rare",
		Price = 12999,
		Currency = "Coins",
	},

		
	{
		Id = "MagicianBanana",
		Name = "Magician Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Rare",
		Price = 12999,
		Currency = "Coins",
	},

	{
		Id = "GalaxyBanana",
		Name = "Galaxy Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Epic",
		Price = 24999,
		Currency = "Coins",
	},
	{
		Id = "SemuraiBanana",
		Name = "Semurai Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Epic",
		Price = 49999,
		Currency = "Coins",
	},
	{
		Id = "HealerLordBanana",
		Name = "Healer Lord Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Legendary",
		Price = 599,
		Currency = "Robux",
	},

}

return Skins


-- rarity , common, rare, epic, legendary