local Skins = {

	{
		Id = "SleepyBanana",
		Name = "Sleepy Banana",
		Image = "rbxassetid://101709420966439",
		Rarity = "Common",
		Price = 0,
		Currency = "Coins",
	},

	{
		Id = "CoolBanana",
		Name = "Cool Banana",
		Image = "rbxassetid://122492456684024",
		Rarity = "Rare",
		Price = 1200,
		Currency = "Coins",
	},

	{
		Id = "JackLantern",
		Name = "Jack O Lantern",
		Image = "rbxassetid://103958840548469",
		Rarity = "Epic",
		Price = 5999,
		Currency = "Coins",
	},

	{
		Id = "GalaxyBanana",
		Name = "Galaxy Banana",
		Image = "rbxassetid://77545653351880",
		Rarity = "Epic",
		Price = 12999,
		Currency = "Coins",
	},
}

return Skins