local RarityConfig = {

	Common = {
		Name = "Common",
		Background = "rbxassetid://130287616337739",
		Color = Color3.fromRGB(180,180,180),
	},

	Rare = {
		Name = "Rare",
		Background = "rbxassetid://102426415606820",
		Color = Color3.fromRGB(0,170,255),
	},

	Epic = {
		Name = "Epic",
		Background = "rbxassetid://94134262210414",
		Color = Color3.fromRGB(170,85,255),
	},

	Legendary = {
		Name = "Legendary",
		Background = "rbxassetid://111415095133320",
		Color = Color3.fromRGB(255,170,0),
	},

	 Mythic = {
		Name = "Mythic",
		Background = "rbxassetid://137906952419654",
		Color = Color3.fromRGB(218, 65, 0),
	},

}

return RarityConfig