local SkinVisualConfig = {

	SleepyBanana = {

		Head = "SleepyBananaHead",

		BodyColor = Color3.fromRGB(
			255,
			221,
			74
		),

		Parts = {
           UpperTorso = "UpperTorso",
        --    RightLowerArm = "RightLowerArm",
		   RightHand = "RightHand"
        },

		Accessories = {
			Pendant = true
			-- Sword = true,
			-- BackPack = true
		},

	},

	CoolBanana = {

		Head = "CoolBananaHead",

		Parts = {},

		Accessories = {
			BackPack = true
		},

	},

	JackLantern = {

		Head = "JackLanternHead",

		Parts = {},

		Accessories = {},

	},

	GalaxyBanana = {

		Head = "GalaxyBananaHead",

		Parts = {},

		Accessories = {},

	},

}

return SkinVisualConfig